services:
  relay-mysql:
    container_name: relay-mysql
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=relay'
      - 'MYSQL_ROOT_PASSWORD=root123'
      - 'MYSQL_USER=relay_user'
      - 'MYSQL_PASSWORD=relay_pass'
    ports:
      - '3306:3306'
  relay-redis:
    container_name: relay-redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
  relay-mq:
    container_name: relay-mq
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
