spring:
  netty:
    leak-detection: paranoid
  r2dbc:
    url: r2dbc:mysql://localhost:3306/relay
    username: relay_user
    password: relay_pass
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: never
      schema-locations: sql/schema.sql
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3000
      timeout: 3000 # read timeout
#  jmx:
#    enabled: true

external:
  relay:
    base-url: http://localhost:8090/relay-api
    uris:
      get-one-path: /api/v1/relay/{relayId}
      get-all-path: /api/v1/relay
      save-path: /api/v1/relay
      modify-path: /api/v1/relay/{relayId}
      delete-path: /api/v1/relay/{relayId}


logging:
  level:
    root: debug
    web: debug
    sun.rmi: info
    javax.management: info
    javax.management.remote.rmi: info
    sun.rmi.transport.tcp: info
    sun.rmi.loader: info
  pattern:
    level: "%5p [TRACE_ID:%X{trace_id} SPAN_ID:%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  endpoints:
#    jmx:
#      exposure:
#        include: '*'
#  jmx:
#    metrics:
#      export:
#        enabled: true

custom-netty:
  read-timeout: 4000
  write-timeout: 4000
  worker-thread-count: 4
  selector-count: 2
  daemon-thread: false