
custom-netty:
  read-timeout:
  write-timeout:
  connection-timeout: 5s
  idle-timeout: 30s
  max-keep-alive-requests:
  validate-headers: true
  initial-buffer-size:
  max-initial-line-length:
  h2c-max-content-length:
  worker-threads: 4


spring:
  application:
    name: relay-api

